### ISSUE TITLE
Permanent networks with end date far in the future

### ISSUE THREAD

**Issue by javiquinte** [GEOFON/routing#4]
If time windows have unreallistic dates (e.g. year 2999) some problems could appear when trying to calculate overlaps. Now there is a fix maximum date (2100), but it should be solved in a better way.

**Comment by pevans-gfz** [comment]
Leave the end attribute empty, or undefined. Users should expect that this field is not supplied.

**Comment by javiquinte** [comment]
The ranges of time windows and the calculation of overlap is a little bit tricky. In particular when the four values can be "undefined". A workaround can be found in commit aa3c052fc7a631a532012e06dc7e77783e02d16f . A minimum and maximum date have been internally defined (1900 and 3000 respectively) and when an undefined value is passed, it is replaced with one of these two, depending on the context.
I'll close this now, but a better solution should be probably implemented.
